@baseUrl = http://localhost:3000
@token = 

### Login
POST {{baseUrl}}/api/auth/login 
Content-Type: "application/json"

{
    "username":"admin1",
    "password":"admin123"
}

### Add New User
POST {{baseUrl}}/api/user-management/add-user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "admin2",
  "password": "admin123",
  "role": "B.BM.ADMIN"
}

### Add New Category
POST {{baseUrl}}/api/category-management/add-new-category
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Programming"
}

### Add New Source
POST {{baseUrl}}/api/source-management/add-new-source
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "detikCom",
  "link": "https://detik.com"
}

### Add New Type
POST {{baseUrl}}/api/type-management/add-new-type
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Video"
}

### Add New Item
POST {{baseUrl}}/api/item-management/add-new-item
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "New Item Title",
  "link": "https://example.com/new-item",
  "notes": "Some notes about this item",
  "category": "category-uuid-here",
  "source": "source-uuid-here",
  "type": "type-uuid-here",
  "creator": "creator-uuid-here"
}

### Add New Creator
POST {{baseUrl}}/api/creator-management/add-new-creator
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "New Creator",
  "link": "https://example.com/new-creator"
}

### Get All Creator By User
GET {{baseUrl}}/api/creator-management/get-creator-by-user
Content-Type: application/json
Authorization: Bearer {{token}}

